### ISSUE TITLE
Why not use `laravel-precognition`

### ISSUE THREAD

**Issue by TouchSek** [sot1986/nuxt-laravel-precognition#1]
Laravel has https://www.npmjs.com/package/laravel-precognition as its core library, so we better use it.

**Comment by sot1986** [comment]
> Laravel has https://www.npmjs.com/package/laravel-precognition as its core library, so we better use it.

That package use axios. This one not.

**Comment by TouchSek** [comment]
I see. thanks.

**Comment by TouchSek** [comment]
@sot1986 and how to integrate with this package?
https://github.com/manchenkoff/nuxt-auth-sanctum

**Comment by sot1986** [comment]
Sanctum is one package to authenticate spa or generate access token. Precognition is Laravel Middleware to sync frontend and backend form validation (in realtime). Users may need only one of them...

**Comment by sot1986** [comment]
If you don't have further questions I would close this issue.

Please confirm, thanks.

**Comment by TouchSek** [comment]
Ok, thanks. no more.
